// <auto-generated />
using System;
using DotNetCore6Test.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetCore6Test.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220828213458_PostsAndComments")]
    partial class PostsAndComments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DotNetCore6Test.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("longblob");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("850ad099-f3f5-4315-a03f-ea45025cc65c"),
                            Email = "test@test.com",
                            FirstName = "First",
                            IsAdmin = true,
                            LastName = "Last",
                            PasswordHash = new byte[] { 229, 73, 110, 178, 184, 91, 9, 87, 183, 200, 48, 14, 119, 32, 198, 154, 13, 170, 51, 81, 134, 138, 87, 243, 86, 175, 80, 201, 212, 158, 140, 104, 174, 179, 208, 110, 148, 251, 219, 14, 241, 190, 170, 131, 139, 31, 68, 11, 97, 251, 57, 15, 160, 199, 133, 243, 169, 49, 4, 4, 87, 220, 207, 98 },
                            PasswordSalt = new byte[] { 224, 201, 228, 137, 158, 5, 30, 39, 183, 8, 99, 89, 244, 189, 106, 109, 212, 42, 26, 201, 139, 54, 250, 212, 35, 124, 79, 18, 24, 221, 206, 83, 9, 172, 227, 43, 59, 32, 139, 142, 39, 252, 59, 133, 65, 42, 228, 133, 181, 1, 94, 124, 69, 157, 218, 81, 222, 153, 131, 181, 222, 107, 19, 176, 57, 229, 63, 244, 93, 105, 139, 106, 88, 204, 204, 3, 124, 204, 158, 234, 115, 34, 213, 141, 127, 134, 235, 177, 2, 124, 124, 229, 6, 128, 23, 47, 115, 29, 188, 46, 199, 168, 155, 194, 239, 143, 75, 122, 57, 78, 58, 57, 17, 80, 255, 27, 49, 166, 127, 245, 138, 29, 20, 225, 93, 143, 141, 153 },
                            Username = ""
                        });
                });

            modelBuilder.Entity("DotNetCore6Test.Entities.Auth.UserLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LoginTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("DotNetCore6Test.Entities.Forum.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PostId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("DotNetCore6Test.Entities.Forum.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
